
fos_rest:
    exception:
        enabled: true
    view:
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml, css ], fallback_format: html, prefer_extension: false }
