security:
    # *NEVER* store passwords as plaintext in production, this is purely for
    # demo purposes.
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_CAN_VIEW_NON_PUBLISHED]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                # Only for demo purposes. Of course, use a more
                # secure password on production.
                users:
                    anna_admin: { password: kitten, roles: ROLE_ADMIN }
                    admin:      { password: admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: ~

    access_control:
        - { path: ^(/(de|fr|en))?/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
