# Sensiolabs Insight configuration
#
# Please remove this file if you start a real project. It's not intended for production use.
#

global_exclude_dirs:
    - vendor
    - public
    - tests
    - vagrant
    - bin

pre_composer_script: |
    #!/bin/bash

    cp config/fixtures/parameters.yml.dist config/packages/parameters.yml
    cp config/fixtures/phpcr_doctrine_dbal.yml.dist config/packages/phpcr.yml


rules:
    symfony.web_config_should_not_be_present:
        enabled: false
