Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  config.vm.host_name = "cmfsandbox"

  config.vm.customize do |vm|
    vm.memory_size = 256
    vm.name = "cmfsandbox"
  end

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  config.vm.network :hostonly, "33.33.33.10"

  config.vm.share_folder "app", "/app", "..", :nfs => true

  # create jackrabbit folder in repo and uncomment line if you want to keep your
  # repository outside the vm
  # config.vm.share_folder "jackrabbit", "/opt/jackrabbit/repository", "../jackrabbit"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path  = "modules"
    puppet.manifest_file  = "sandbox.pp"
  end
end
