services:
    sandbox_admin.controller:
        class: Sandbox\AdminBundle\Controller\ContentController
        arguments:
            container: "@service_container"
        shared: true
    sandbox.admin.admin.static_editable_content:
        class: Sandbox\AdminBundle\Admin\ContentAdmin
        tags:
            - {name: sonata.admin, manager_type: phpcr, group: phpcr, label: content}
        arguments: ["",Sandbox\MainBundle\Document\EditableStaticContent, "SandboxAdminBundle:ContentAdmin"]
        calls:
            - [ setRouteBuilder, [ @sonata.admin.route.path_info_slashes ] ]
    sandbox.admin.admin.navigation:
        class: Sandbox\AdminBundle\Admin\NavigationAdmin
        tags:
            - {name: sonata.admin, manager_type: phpcr, group: phpcr, label: navigation}
        arguments: ["",Symfony\Cmf\Bundle\NavigationBundle\Document\Navigation, "SandboxAdminBundle:NavigationAdmin"]
        calls:
            - [ setRouteBuilder, [ @sonata.admin.route.path_info_slashes ] ]



