App\Document\DemoNewsContent:
    definitions:
        - { uri_schema: '/news/{date}/{title}' }
    token_providers:
        date: [content_datetime, { method: getDate, date_format: Y-m-d }]
        title: [content_method, {method: getTitle, slugify: true }]
