#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new AppKernel('prod', false);

$application = new Application($kernel);
$application->run();
