services:
    sandbox_main.controller:
        class: Sandbox\MainBundle\Controller\ContentController
        calls:
            - [ setContainer, [@service_container] ]

    sandbox_main.debugListener:
        class: Sandbox\MainBundle\EventListener\SandboxExceptionListener
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - {name: "kernel.event_subscriber"}